run:
  timeout: 5m
  go: '1.26'

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - misspell
    - gocritic
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

  govet:
    enable-all: true
    disable:
      - fieldalignment

issues:
  max-issues-per-linter: 50
  max-same-issues: 3

severity:
  default-severity: warning
